const MessageService = require('../services/message')

let IO = null
module.exports = (io) => {
	if(io) 
		IO = io
	
	// data = {sender, receiver, id, message: {type, [type], reply_to}, createdAt, updatedAt}
	const sendMessage = async function (data) {
		try {
			const socket = this


			// do nothing if text is empty 
			if(data.message.type === 'text' && data.message.text === '') {
				return;
			}


			// save message to database.
			// const message = await MessageService.sendMessage(data.sender, data.receiver, data.message)


		
			// these values are auto generated by database.
			// data.id = message.id
			// data.date = message.createdAt
		
			// send message to receiver (user or group)

			// io.in(data.sender).emit("/newMessage", data)

			console.log("sendMessage to: ", data.receiver, data)
			IO.in(data.receiver).emit("/newMessage", data)

		} catch(err) {
			console.log(err)
		}

	} 

	const connectUser = function (data) {
		const socket = this
		socket.join(data.id)
		//console.log("joined room: ", data.id)
	}

	const disconnectUser = function (data) {
		const socket = this
		//console.log("Leaving room " + data.id)
		socket.leave(data.id)
	}

	return {
		sendMessage,
		connectUser,
		disconnectUser
	}
}